services:
  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - backend

  # Servicio para el backend en Spring Boot
  app:
    build: ./  # Esto indica que el backend está en la raíz del proyecto
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin
      OLLAMA_URL: http://host.docker.internal:11434  # Cambiar a host.docker.internal
    ports:
      - "8080:8080"
    networks:
      - backend
    command: /wait-for-it.sh db:5432 -- ./gradlew bootRun --no-daemon

  # Servicio para el frontend en React
  frontend:
    build: ./react-frontend  # Carpeta donde está tu aplicación React
    ports:
      - "3000:3000"  # Exponer el puerto 3000 del frontend
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
