version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      context: .  # Apunta a la raíz del proyecto (donde está el backend)
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - backend
    command: /wait-for-it.sh db:5432 -- ./gradlew bootRun --no-daemon

  frontend:
    build:
      context: ./react-frontend  # Apunta a la carpeta de React
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - app  # El frontend depende del backend

networks:
  backend:
    driver: bridge
